Vagrant.configure("2") do |config|
  nodes = 3
  (1..nodes).each do |i|
    config.vm.define "node#{i}" do |config|
      config.vm.box = "ubuntu/bionic64"
      config.vm.hostname = "kube#{i}"
      config.vm.network "forwarded_port", guest: 22, host: "8#{i}22".to_i, id: "ssh"
      config.vm.network "public_network", ip: "192.168.0.8#{i}", bridge: "en1: Wi-Fi (AirPort)"
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.check_guest_additions = false
      end
      config.vm.provision "shell",
        inline: "sed -i 's|archive\.ubuntu\.com|mirror.kakao.com|g' /etc/apt/sources.list"
      config.vm.provision "shell",
        inline: "DEBIAN_FRONTEND=noninteractive apt-get update > /dev/null"
    end
  end

end
